version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v0
    platform: linux/arm64/v8
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight web UI
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

volumes:
  redis_data:
    driver: local 