version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    platform: linux/arm64/v8
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight web UI
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_ARGS="--loadmodule /opt/redis-stack/lib/redisearch.so"
    restart: unless-stopped

volumes:
  redis_data:
    driver: local 